// ZUTOMAYO Discography Data
// Trilingual: JA / KR / EN
// lyrics_ja / lyrics_kr / lyrics_en — populate manually or via fetch

const ZUTOMAYO = {
  artist: {
    name_ja:    'ずっと真夜中でいいのに。',
    name_kr:    '계속 한밤중이어도 좋아.',
    name_en:    'ZUTOMAYO',
    romanized:  'Zutto Mayonaka de Iinoni.',
    description_ja: '2018年デビューの日本のバンド。作詞作曲・ボーカルを担当するACAねを中心に活動。',
    description_kr: '2018년 데뷔한 일본 밴드. 작사작곡과 보컬을 담당하는 ACA네를 중심으로 활동.',
    description_en: 'Japanese band that debuted in 2018, centered on ACAne who handles all songwriting and vocals.',
  },

  albums: [
    {
      id:         'tadashii',
      title_ja:   '正しい偽りからの起床',
      title_kr:   '올바른 거짓으로부터의 기상',
      title_en:   'Waking from the Righteous Lie',
      romanized:  'Tadashii Itsuwari kara no Kishou',
      year:       2018,
      month:      10,
      type:       'Mini-Album',
      type_kr:    '미니 앨범',
      cover:      'music/covers/tadashii.jpg',
      tracks: [
        {
          id:         'byoshin',
          track:      1,
          title_ja:   '秒針を噛む',
          title_kr:   '초침을 씹다',
          title_en:   'Chewing the Second Hand',
          romanized:  'Byoushin wo Kamu',
          youtube_id: 'GJI4Gv7NbmE',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'obenkyou',
          track:      2,
          title_ja:   'お勉強しといてよ',
          title_kr:   '공부해 두세요',
          title_en:   'Please Study',
          romanized:  'Obenkyou Shitoi te yo',
          youtube_id: 'Atvsg_zogxo',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'mabushii',
          track:      3,
          title_ja:   '眩しいDNAだけ',
          title_kr:   '눈부신 DNA만',
          title_en:   'Just the Dazzling DNA',
          romanized:  'Mabushii DNA dake',
          youtube_id: 'VJy8qZ77bpE',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'kirakiller',
          track:      4,
          title_ja:   '綺羅キラー',
          title_kr:   '기라 킬러',
          title_en:   'Kira Killer',
          romanized:  'Kira Kiraa',
          youtube_id: 'e5LaKxJVeVI',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'tadashikunarenai',
          track:      5,
          title_ja:   '正しくなれない',
          title_kr:   '올바를 수 없어',
          title_en:   "Can't Be Right",
          romanized:  'Tadashiku Narenai',
          youtube_id: '258qUAI7rck',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'zanki',
          track:      6,
          title_ja:   '残機',
          title_kr:   '잔기',
          title_en:   'Remaining Lives',
          romanized:  'Zanki',
          youtube_id: '6OC92oxs4gA',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
      ],
    },

    {
      id:         'imawa',
      title_ja:   '今は今で誓いは笑みで',
      title_kr:   '지금은 지금으로 맹세는 미소로',
      title_en:   'Now and Now, Vows with a Smile',
      romanized:  'Ima wa Ima de Chikai wa Emi de',
      year:       2019,
      month:      4,
      type:       'EP',
      type_kr:    'EP',
      cover:      'music/covers/imawa.jpg',
      tracks: [
        {
          id:         'kangure',
          track:      1,
          title_ja:   '勘ぐれい',
          title_kr:   '수상한 그레이',
          title_en:   'Suspicious Gray',
          romanized:  'Kangure',
          youtube_id: 'ugpywe34_30',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'teiketsuvolt',
          track:      2,
          title_ja:   '低血ボルト',
          title_kr:   '저혈 볼트',
          title_en:   'Low Blood Voltage',
          romanized:  'Teiketsu Boruto',
          youtube_id: 'COll6PdtI5w',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'humanoid',
          track:      3,
          title_ja:   'ヒューマノイド',
          title_kr:   '휴머노이드',
          title_en:   'Humanoid',
          romanized:  'Hyuumanoiddo',
          youtube_id: 'GAB26GgJ8V8',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'usomo',
          track:      4,
          title_ja:   '嘘も本当も君だから',
          title_kr:   '거짓도 진심도 너이기에',
          title_en:   "Both Lies and Truth Are Because of You",
          romanized:  'Uso mo Hontou mo Kimi dakara',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'yasashiikiseten',
          track:      5,
          title_ja:   '優しい気持ちで起こして',
          title_kr:   '부드러운 마음으로 깨워줘',
          title_en:   'Wake Me with Gentle Feelings',
          romanized:  'Yasashii Kimochi de Okoshite',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'saisho',
          track:      6,
          title_ja:   '最初から今まで',
          title_kr:   '처음부터 지금까지',
          title_en:   'From the Very Beginning Until Now',
          romanized:  'Saisho kara Ima made',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
      ],
    },

    {
      id:         'sensenwa',
      title_ja:   '潜潜話',
      title_kr:   '잠잠한 이야기',
      title_en:   'Whispered Tales',
      romanized:  'Sensenwa',
      year:       2019,
      month:      10,
      type:       'Full Album',
      type_kr:    '정규 앨범',
      cover:      'music/covers/sensenwa.jpg',
      tracks: [
        {
          id:         'byoshin_v2',
          track:      1,
          title_ja:   '秒針を噛む',
          title_kr:   '초침을 씹다',
          title_en:   'Chewing the Second Hand',
          romanized:  'Byoushin wo Kamu',
          youtube_id: 'GJI4Gv7NbmE',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'obenkyou_v2',
          track:      2,
          title_ja:   'お勉強しといてよ',
          title_kr:   '공부해 두세요',
          title_en:   'Please Study',
          romanized:  'Obenkyou Shitoi te yo',
          youtube_id: 'Atvsg_zogxo',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'kangure_v2',
          track:      3,
          title_ja:   '勘ぐれい',
          title_kr:   '수상한 그레이',
          title_en:   'Suspicious Gray',
          romanized:  'Kangure',
          youtube_id: 'ugpywe34_30',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'humanoid_v2',
          track:      4,
          title_ja:   'ヒューマノイド',
          title_kr:   '휴머노이드',
          title_en:   'Humanoid',
          romanized:  'Hyuumanoiddo',
          youtube_id: 'GAB26GgJ8V8',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'teiketsuvolt_v2',
          track:      5,
          title_ja:   '低血ボルト',
          title_kr:   '저혈 볼트',
          title_en:   'Low Blood Voltage',
          romanized:  'Teiketsu Boruto',
          youtube_id: 'COll6PdtI5w',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'mabushii_v2',
          track:      6,
          title_ja:   '眩しいDNAだけ',
          title_kr:   '눈부신 DNA만',
          title_en:   'Just the Dazzling DNA',
          romanized:  'Mabushii DNA dake',
          youtube_id: 'VJy8qZ77bpE',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'usomo_v2',
          track:      7,
          title_ja:   '嘘も本当も君だから',
          title_kr:   '거짓도 진심도 너이기에',
          title_en:   'Both Lies and Truth Are Because of You',
          romanized:  'Uso mo Hontou mo Kimi dakara',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'kirakiller_v2',
          track:      8,
          title_ja:   '綺羅キラー',
          title_kr:   '기라 킬러',
          title_en:   'Kira Killer',
          romanized:  'Kira Kiraa',
          youtube_id: 'e5LaKxJVeVI',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'tadashikunarenai_v2',
          track:      9,
          title_ja:   '正しくなれない',
          title_kr:   '올바를 수 없어',
          title_en:   "Can't Be Right",
          romanized:  'Tadashiku Narenai',
          youtube_id: '258qUAI7rck',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'zanki_v2',
          track:      10,
          title_ja:   '残機',
          title_kr:   '잔기',
          title_en:   'Remaining Lives',
          romanized:  'Zanki',
          youtube_id: '6OC92oxs4gA',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'yasashii_v2',
          track:      11,
          title_ja:   '優しい気持ちで起こして',
          title_kr:   '부드러운 마음으로 깨워줘',
          title_en:   'Wake Me with Gentle Feelings',
          romanized:  'Yasashii Kimochi de Okoshite',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'itsuka',
          track:      12,
          title_ja:   'いつかまた',
          title_kr:   '언젠가 다시',
          title_en:   'Someday Again',
          romanized:  'Itsuka Mata',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'grayzone',
          track:      13,
          title_ja:   'グレーゾーン',
          title_kr:   '그레이 존',
          title_en:   'Gray Zone',
          romanized:  'Gure Zone',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
      ],
    },

    {
      id:         'gusare',
      title_ja:   'ぐされ',
      title_kr:   '썩어',
      title_en:   'Decompose',
      romanized:  'Gusare',
      year:       2021,
      month:      2,
      type:       'Full Album',
      type_kr:    '정규 앨범',
      cover:      'music/covers/gusare.jpg',
      tracks: [
        {
          id:         'hazehaseru',
          track:      1,
          title_ja:   'ハゼ馳せる果てるまで',
          title_kr:   '망둥어가 달리는 끝까지',
          title_en:   'Until the Goby Runs to the End',
          romanized:  'Haze Haseru Hateru made',
          youtube_id: 'ElnxZtiBDvs',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'aitsura',
          track:      2,
          title_ja:   'あいつら全員同窓会',
          title_kr:   '그들 전원 동창회',
          title_en:   "Everyone's at the Reunion",
          romanized:  'Aitsura Zenin Dosoukai',
          youtube_id: 'ZUwaudw8ht0',
          has_mv:     true,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'mabayui',
          track:      3,
          title_ja:   'まばゆい',
          title_kr:   '눈부셔',
          title_en:   'Dazzling',
          romanized:  'Mabayui',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'kabegiwa',
          track:      4,
          title_ja:   '壁際でひとり',
          title_kr:   '벽가에 혼자',
          title_en:   'Alone by the Wall',
          romanized:  'Kabegiwa de Hitori',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'doukoku',
          track:      5,
          title_ja:   '胴体着陸',
          title_kr:   '동체 착륙',
          title_en:   'Belly Landing',
          romanized:  'Doutai Chakuriku',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'fukashigi',
          track:      6,
          title_ja:   '不可思議のカルテ',
          title_kr:   '불가사의한 카르테',
          title_en:   'Mysterious Medical Chart',
          romanized:  'Fukashigi no Karute',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         '20yo',
          track:      7,
          title_ja:   '20歳になったかつての子供たちへ',
          title_kr:   '20살이 된 한때의 아이들에게',
          title_en:   'To the Children Who Have Now Turned 20',
          romanized:  '20-sai ni Natta Katsute no Kodomotachi e',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'shinkirou',
          track:      8,
          title_ja:   '蜃気楼だった',
          title_kr:   '신기루였어',
          title_en:   'It Was a Mirage',
          romanized:  'Shinkirou datta',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'machigai',
          track:      9,
          title_ja:   '機械油とスペア',
          title_kr:   '기계 기름과 스페어',
          title_en:   'Machine Oil and Spare Parts',
          romanized:  'Kikaikyu to Supea',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'yurete',
          track:      10,
          title_ja:   '揺れる',
          title_kr:   '흔들려',
          title_en:   'Swaying',
          romanized:  'Yurete',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'omoeba',
          track:      11,
          title_ja:   '思えば遠くにきたもんだ',
          title_kr:   '생각해보면 멀리 왔구나',
          title_en:   "When I Think of It, I've Come so Far",
          romanized:  'Omoeba Tooku ni Kita mon da',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'omoide',
          track:      12,
          title_ja:   '思い出せなくなるその日まで',
          title_kr:   '기억할 수 없게 되는 그날까지',
          title_en:   'Until the Day I Can No Longer Remember',
          romanized:  'Omoida se Nakunaru Sono Hi made',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'gusare_end',
          track:      13,
          title_ja:   'ぐされ',
          title_kr:   '썩어',
          title_en:   'Decompose',
          romanized:  'Gusare',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
      ],
    },

    {
      id:         'chinkougaku',
      title_ja:   '沈香学',
      title_kr:   '침향학',
      title_en:   'Agarwood Studies',
      romanized:  'Chinkougaku',
      year:       2023,
      month:      2,
      type:       'Full Album',
      type_kr:    '정규 앨범',
      cover:      'music/covers/chinkougaku.jpg',
      tracks: [
        {
          id:         'kikousha',
          track:      1,
          title_ja:   '機械油とスペア（再録）',
          title_kr:   '기계 기름과 스페어（재녹）',
          title_en:   'Machine Oil and Spare Parts (Re-recorded)',
          romanized:  'Kikaikyu to Supea',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'yakusoku',
          track:      2,
          title_ja:   '約束の森',
          title_kr:   '약속의 숲',
          title_en:   'Forest of Promises',
          romanized:  'Yakusoku no Mori',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'kurai_ii',
          track:      3,
          title_ja:   '暗くなるまで待って',
          title_kr:   '어두워질 때까지 기다려',
          title_en:   'Wait Until Dark',
          romanized:  'Kuraku Naru made Matte',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'byoshin_chin',
          track:      4,
          title_ja:   '秒針を噛む（Re-arrange）',
          title_kr:   '초침을 씹다（리어레인지）',
          title_en:   'Chewing the Second Hand (Re-arrange)',
          romanized:  'Byoushin wo Kamu',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'senkou',
          track:      5,
          title_ja:   '線香',
          title_kr:   '선향',
          title_en:   'Incense Stick',
          romanized:  'Senkou',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'chinkougaku_song',
          track:      6,
          title_ja:   '沈香学',
          title_kr:   '침향학',
          title_en:   'Agarwood Studies',
          romanized:  'Chinkougaku',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'fujiisan',
          track:      7,
          title_ja:   '私たちの国',
          title_kr:   '우리들의 나라',
          title_en:   'Our Country',
          romanized:  'Watashitachi no Kuni',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'hana_chin',
          track:      8,
          title_ja:   '花一目',
          title_kr:   '꽃 한눈',
          title_en:   'A Glimpse of Flowers',
          romanized:  'Hana Hitome',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'daidai',
          track:      9,
          title_ja:   '橙彼方',
          title_kr:   '주황 저편',
          title_en:   'Orange Beyond',
          romanized:  'Daidai Kanata',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'sorekara',
          track:      10,
          title_ja:   'それから',
          title_kr:   '그리고 나서',
          title_en:   'After That',
          romanized:  'Sorekara',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'mori_chin',
          track:      11,
          title_ja:   '森、道、市場',
          title_kr:   '숲, 길, 시장',
          title_en:   'Forest, Road, Market',
          romanized:  'Mori, Michi, Ichiba',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'maboroshi',
          track:      12,
          title_ja:   '幻燈',
          title_kr:   '환등',
          title_en:   'Magic Lantern',
          romanized:  'Gentou',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'ito',
          track:      13,
          title_ja:   '糸を',
          title_kr:   '실을',
          title_en:   'Thread',
          romanized:  'Ito wo',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
      ],
    },

    {
      id:         'koke',
      title_ja:   '虚仮の一念海馬に託す',
      title_kr:   '허접한 신념을 해마에 맡겨',
      title_en:   "Entrusting a Fool's Determination to the Hippocampus",
      romanized:  'Koke no Ichinen Kaiba ni Takusu',
      year:       2024,
      month:      2,
      type:       'Mini-Album',
      type_kr:    '미니 앨범',
      cover:      'music/covers/koke.jpg',
      tracks: [
        {
          id:         'yakitako',
          track:      1,
          title_ja:   '焼き蛸',
          title_kr:   '문어구이',
          title_en:   'Grilled Octopus',
          romanized:  'Yakitako',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'genkaku',
          track:      2,
          title_ja:   '幻覚にて失禮',
          title_kr:   '환각으로 실례합니다',
          title_en:   'Excuse Me Through Hallucination',
          romanized:  'Genkaku nite Shitsure',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'kokenoichi',
          track:      3,
          title_ja:   '虚仮の一念',
          title_kr:   '허접한 신념',
          title_en:   "A Fool's Determination",
          romanized:  'Koke no Ichinen',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'yokubou',
          track:      4,
          title_ja:   '欲望に満ちた青年団',
          title_kr:   '욕망으로 가득한 청년단',
          title_en:   'Youth Group Filled with Desire',
          romanized:  'Yokubou ni Michita Seinandan',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'kaiba',
          track:      5,
          title_ja:   '海馬に託す',
          title_kr:   '해마에 맡겨',
          title_en:   'Entrusting to the Hippocampus',
          romanized:  'Kaiba ni Takusu',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
        {
          id:         'koke_last',
          track:      6,
          title_ja:   'わがまま',
          title_kr:   '제멋대로',
          title_en:   'Selfish',
          romanized:  'Wagamama',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
      ],
    },

    {
      id:         'keimodo',
      title_ja:   '形藻土',
      title_kr:   '형모토',
      title_en:   'Keimodo',
      romanized:  'Keimodo',
      year:       2026,
      month:      1,
      type:       'Full Album',
      type_kr:    '정규 앨범',
      cover:      'music/covers/keimodo.jpg',
      tracks: [
        {
          id:         'keimodo_1',
          track:      1,
          title_ja:   'Track 1',
          title_kr:   'Track 1',
          title_en:   'Track 1',
          romanized:  '',
          youtube_id: '',
          has_mv:     false,
          lyrics_ja:  '',
          lyrics_kr:  '',
          lyrics_en:  '',
        },
      ],
    },
  ],
};
