// Auto-generated by build_prices.py from Mercari Japan data
// RARITY_PRICES = fallback when no per-card data
// CARD_PRICES   = specific prices where available

const RARITY_PRICES = {
  "N": {
    "buy": 300,
    "sell": 300
  },
  "R": {
    "buy": 300,
    "sell": 300
  },
  "SR": {
    "buy": 500,
    "sell": 600
  },
  "UR": {
    "buy": 1500,
    "sell": 1500
  },
  "SEC": {
    "buy": 8000,
    "sell": 8000
  },
  "PR": {
    "buy": 1500,
    "sell": 1500
  }
};

const CARD_PRICES = {
  "cards/zutomayocard_4th_26.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_4th_18.png": {
    "buy": 666,
    "sell": 666
  },
  "cards/zutomayocard_2nd_23.png": {
    "buy": 999,
    "sell": 999
  },
  "cards/zutomayocard_4th_19.png": {
    "buy": 666,
    "sell": 666
  },
  "cards/zutomayocard_1st_10.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_32.png": {
    "buy": 333,
    "sell": 333
  },
  "cards/zutomayocard_1st_16.png": {
    "buy": 344,
    "sell": 500
  },
  "cards/zutomayocard_1st_11.png": {
    "buy": 555,
    "sell": 777
  },
  "cards/zutomayocard_1st_4.png": {
    "buy": 1200,
    "sell": 2000
  },
  "cards/zutomayocard_4th_15.png": {
    "buy": 790,
    "sell": 899
  },
  "cards/zutomayocard_3rd_2.png": {
    "buy": 1444,
    "sell": 1500
  },
  "cards/zutomayocard_4th_20.png": {
    "buy": 1011,
    "sell": 1011
  },
  "cards/zutomayocard_4th_12.png": {
    "buy": 780,
    "sell": 780
  },
  "cards/zutomayocard_1st_21.png": {
    "buy": 300,
    "sell": 366
  },
  "cards/zutomayocard_4th_24.png": {
    "buy": 1100,
    "sell": 1111
  },
  "cards/zutomayocard_4th_6.png": {
    "buy": 4999,
    "sell": 10500
  },
  "cards/zutomayocard_4th_17.png": {
    "buy": 880,
    "sell": 880
  },
  "cards/zutomayocard_4th_31.png": {
    "buy": 880,
    "sell": 880
  },
  "cards/zutomayocard_3rd_48.png": {
    "buy": 350,
    "sell": 350
  },
  "cards/zutomayocard_2nd_7.png": {
    "buy": 320,
    "sell": 600
  },
  "cards/zutomayocard_2nd_11.png": {
    "buy": 800,
    "sell": 800
  },
  "cards/zutomayocard_2nd_14.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_18.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_21.png": {
    "buy": 500,
    "sell": 555
  },
  "cards/zutomayocard_2nd_24.png": {
    "buy": 390,
    "sell": 555
  },
  "cards/zutomayocard_2nd_26.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_2nd_27.png": {
    "buy": 600,
    "sell": 600
  },
  "cards/zutomayocard_2nd_29.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_2nd_30.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_2nd_31.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_32.png": {
    "buy": 444,
    "sell": 555
  },
  "cards/zutomayocard_3rd_23.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_3rd_16.png": {
    "buy": 650,
    "sell": 650
  },
  "cards/zutomayocard_4th_16.png": {
    "buy": 788,
    "sell": 990
  },
  "cards/zutomayocard_4th_1.png": {
    "buy": 2699,
    "sell": 3800
  },
  "cards/zutomayocard_4th_9.png": {
    "buy": 999,
    "sell": 1400
  },
  "cards/zutomayocard_4th_4.png": {
    "buy": 1700,
    "sell": 1799
  },
  "cards/zutomayocard_4th_22.png": {
    "buy": 990,
    "sell": 990
  },
  "cards/zutomayocard_4th_13.png": {
    "buy": 950,
    "sell": 950
  },
  "cards/zutomayocard_4th_10.png": {
    "buy": 990,
    "sell": 1400
  },
  "cards/zutomayocard_4th_7.png": {
    "buy": 1800,
    "sell": 1800
  },
  "cards/zutomayocard_3rd_47.png": {
    "buy": 350,
    "sell": 350
  },
  "cards/zutomayocard_1st_3.png": {
    "buy": 2000,
    "sell": 2000
  },
  "cards/zutomayocard_1st_19.png": {
    "buy": 777,
    "sell": 1100
  },
  "cards/zutomayocard_2nd_6.png": {
    "buy": 600,
    "sell": 900
  },
  "cards/zutomayocard_2nd_5.png": {
    "buy": 900,
    "sell": 900
  },
  "cards/zutomayocard_2nd_3.png": {
    "buy": 900,
    "sell": 1200
  },
  "cards/zutomayocard_1st_2.png": {
    "buy": 1500,
    "sell": 2300
  },
  "cards/zutomayocard_1st_1.png": {
    "buy": 3800,
    "sell": 4200
  },
  "cards/zutomayocard_1st_18.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_26.png": {
    "buy": 750,
    "sell": 750
  },
  "cards/zutomayocard_1st_22.png": {
    "buy": 300,
    "sell": 750
  },
  "cards/zutomayocard_1st_9.png": {
    "buy": 595,
    "sell": 750
  },
  "cards/zutomayocard_3rd_7.png": {
    "buy": 499,
    "sell": 750
  },
  "cards/zutomayocard_1st_5.png": {
    "buy": 750,
    "sell": 750
  },
  "cards/zutomayocard_2nd_1.png": {
    "buy": 5200,
    "sell": 5200
  },
  "cards/zutomayocard_1st_28.png": {
    "buy": 480,
    "sell": 666
  },
  "cards/zutomayocard_3rd_10.png": {
    "buy": 700,
    "sell": 1200
  },
  "cards/zutomayocard_2nd_12.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_2nd_13.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_3rd_25.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_3rd_29.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_2nd_28.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_1st_7.png": {
    "buy": 499,
    "sell": 499
  },
  "cards/zutomayocard_1st_25.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_27.png": {
    "buy": 500,
    "sell": 500
  },
  "cards/zutomayocard_1st_29.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_3rd_19.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_3rd_26.png": {
    "buy": 400,
    "sell": 450
  },
  "cards/zutomayocard_3rd_31.png": {
    "buy": 450,
    "sell": 450
  },
  "cards/zutomayocard_3rd_53.png": {
    "buy": 350,
    "sell": 350
  },
  "cards/zutomayocard_3rd_12.png": {
    "buy": 500,
    "sell": 555
  },
  "cards/zutomayocard_3rd_15.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_1st_12.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_15.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_23.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_24.png": {
    "buy": 499,
    "sell": 499
  },
  "cards/zutomayocard_1st_51.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_47.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_42.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_31.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_102.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_16.png": {
    "buy": 699,
    "sell": 1000
  },
  "cards/zutomayocard_2nd_15.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_54.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_33.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_36.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_53.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_55.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_35.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_65.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_85.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_83.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_81.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_68.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_67.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_84.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_52.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_63.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_49.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_104.png": {
    "buy": 400,
    "sell": 400
  },
  "cards/zutomayocard_2nd_103.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_100.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_99.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_77.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_78.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_79.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_40.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_39.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_57.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_38.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_92.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_19.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_91.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_88.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_90.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_72.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_69.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_43.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_61.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_45.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_44.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_75.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_98.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_97.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_96.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_95.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_76.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_74.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_34.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_82.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_83.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_86.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_66.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_81.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_48.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_49.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_63.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_100.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_77.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_104.png": {
    "buy": 4300,
    "sell": 4300
  },
  "cards/zutomayocard_1st_78.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_58.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_38.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_42.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_70.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_88.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_90.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_89.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_91.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_46.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_61.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_75.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_93.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_1st_74.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_22.png": {
    "buy": 300,
    "sell": 1111
  },
  "cards/zutomayocard_3rd_106.png": {
    "buy": 10000,
    "sell": 10000
  },
  "cards/zutomayocard_3rd_32.png": {
    "buy": 333,
    "sell": 750
  },
  "cards/zutomayocard_3rd_22.png": {
    "buy": 750,
    "sell": 750
  },
  "cards/zutomayocard_3rd_62.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_60.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_44.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_40.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_36.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_35.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_2nd_106.png": {
    "buy": 16555,
    "sell": 16555
  },
  "cards/zutomayocard_3rd_63.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_58.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_3rd_61.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_59.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_55.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_50.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_39.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_14.png": {
    "buy": 450,
    "sell": 450
  },
  "cards/zutomayocard_3rd_57.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_43.png": {
    "buy": 300,
    "sell": 300
  },
  "cards/zutomayocard_3rd_81.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_3rd_95.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_3rd_56.png": {
    "buy": 888,
    "sell": 888
  },
  "cards/zutomayocard_1st_101.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_1st_69.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_1st_37.png": {
    "buy": 777,
    "sell": 777
  },
  "cards/zutomayocard_1st_6.png": {
    "buy": 750,
    "sell": 2500
  },
  "cards/zutomayocard_2nd_9.png": {
    "buy": 600,
    "sell": 1550
  },
  "cards/zutomayocard_1st_45.png": {
    "buy": 333,
    "sell": 333
  },
  "cards/zutomayocard_2nd_2.png": {
    "buy": 850,
    "sell": 1000
  },
  "cards/zutomayocard_4th_33.png": {
    "buy": 666,
    "sell": 666
  },
  "cards/zutomayocard_4th_30.png": {
    "buy": 1111,
    "sell": 1300
  },
  "cards/zutomayocard_4th_3.png": {
    "buy": 2800,
    "sell": 45000
  },
  "cards/zutomayocard_4th_105.png": {
    "buy": 6555,
    "sell": 7550
  },
  "cards/zutomayocard_4th_28.png": {
    "buy": 880,
    "sell": 1050
  },
  "cards/zutomayocard_4th_8.png": {
    "buy": 755,
    "sell": 900
  },
  "cards/zutomayocard_3rd_28.png": {
    "buy": 777,
    "sell": 950
  },
  "cards/zutomayocard_3rd_8.png": {
    "buy": 1500,
    "sell": 1750
  },
  "cards/zutomayocard_1st_14.png": {
    "buy": 550,
    "sell": 650
  },
  "cards/zutomayocard_1st_13.png": {
    "buy": 500,
    "sell": 600
  },
  "cards/zutomayocard_1st_17.png": {
    "buy": 750,
    "sell": 900
  },
  "cards/zutomayocard_1st_8.png": {
    "buy": 800,
    "sell": 950
  },
  "cards/zutomayocard_2nd_8.png": {
    "buy": 2500,
    "sell": 3000
  },
  "cards/zutomayocard_3rd_9.png": {
    "buy": 800,
    "sell": 950
  },
  "cards/zutomayocard_3rd_24.png": {
    "buy": 599,
    "sell": 700
  },
  "cards/zutomayocard_3rd_4.png": {
    "buy": 800,
    "sell": 950
  },
  "cards/zutomayocard_3rd_13.png": {
    "buy": 700,
    "sell": 850
  },
  "cards/zutomayocard_1st_40.png": {
    "buy": 530,
    "sell": 650
  },
  "cards/zutomayocard_3rd_11.png": {
    "buy": 450,
    "sell": 550
  },
  "cards/zutomayocard_2nd_17.png": {
    "buy": 333,
    "sell": 400
  },
  "cards/zutomayocard_3rd_5.png": {
    "buy": 2000,
    "sell": 2350
  },
  "cards/zutomayocard_3rd_27.png": {
    "buy": 1700,
    "sell": 2000
  },
  "cards/zutomayocard_2nd_25.png": {
    "buy": 600,
    "sell": 700
  },
  "cards/zutomayocard_3rd_17.png": {
    "buy": 499,
    "sell": 600
  },
  "cards/zutomayocard_3rd_6.png": {
    "buy": 1100,
    "sell": 1300
  },
  "cards/zutomayocard_3rd_33.png": {
    "buy": 350,
    "sell": 400
  },
  "cards/zutomayocard_2nd_105.png": {
    "buy": 3199,
    "sell": 3700
  },
  "cards/zutomayocard_1st_30.png": {
    "buy": 300,
    "sell": 350
  },
  "cards/zutomayocard_2nd_34.png": {
    "buy": 300,
    "sell": 350
  },
  "cards/zutomayocard_2nd_66.png": {
    "buy": 300,
    "sell": 350
  },
  "cards/zutomayocard_2nd_10.png": {
    "buy": 500,
    "sell": 600
  },
  "cards/zutomayocard_2nd_73.png": {
    "buy": 300,
    "sell": 350
  },
  "cards/zutomayocard_1st_33.png": {
    "buy": 300,
    "sell": 350
  },
  "cards/zutomayocard_3rd_1.png": {
    "buy": 72200,
    "sell": 83050
  },
  "cards/zutomayocard_3rd_20.png": {
    "buy": 888,
    "sell": 1050
  },
  "cards/zutomayocard_3rd_105.png": {
    "buy": 9000,
    "sell": 10350
  },
  "cards/zutomayocard_3rd_21.png": {
    "buy": 499,
    "sell": 600
  },
  "cards/zutomayocard_1st_105.png": {
    "buy": 2519,
    "sell": 2950
  },
  "cards/zutomayocard_4th_27.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_4th_25.png": {
    "buy": 555,
    "sell": 555
  },
  "cards/zutomayocard_4th_2.png": {
    "buy": 3000,
    "sell": 3000
  },
  "cards/zutomayocard_4th_107.png": {
    "buy": 9499,
    "sell": 55000
  },
  "cards/zutomayocard_4th_106.png": {
    "buy": 10500,
    "sell": 12050
  },
  "cards/zutomayocard_4th_5.png": {
    "buy": 3000,
    "sell": 3550
  },
  "cards/zutomayocard_3rd_104.png": {
    "buy": 400,
    "sell": 500
  },
  "cards/zutomayocard_1st_106.png": {
    "buy": 3000,
    "sell": 3550
  },
  "cards/zutomayocard_2nd_4.png": {
    "buy": 3899,
    "sell": 4500
  },
  "cards/zutomayocard_3rd_37.png": {
    "buy": 1000,
    "sell": 1200
  }
};
